config/routes.rb
Refactor::Application.routes.draw do |map|
  resources :snippets do
    resources :refactorings
  end

  devise_for :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/refactoring.rb
class Refactoring < ActiveRecord::Base
  belongs_to :snippet
  belongs_to :user

  validates :snippet_id, :presence => true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  has_many :refactorings
  belongs_to :user

  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :snippets
  has_many :refactors

  # Include default devise modules. Others available are:
  # :token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :username

  validates :email, :uniqueness => true, :format => /\A[^@\s]+@[^@\s]+\Z/
  validates :username, :uniqueness => true, :format => /^([a-z0-9_-]|\s)+$/i,
    :length => 2..20

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/refactorings_controller.rb
class RefactoringsController < ApplicationController
  before_filter :capture_snippet

  # GET /refactorings
  # GET /refactorings.xml
  def index
    @refactorings = Refactoring.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @refactorings }
    end
  end

  # GET /refactorings/1
  # GET /refactorings/1.xml
  def show
    @refactoring = Refactoring.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @refactoring }
    end
  end

  # GET /refactorings/new
  # GET /refactorings/new.xml
  def new
    @refactoring = @snippet ? @snippet.refactorings.build : Refactoring.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @refactoring }
    end
  end

  # GET /refactorings/1/edit
  def edit
    @refactoring = Refactoring.find(params[:id])
  end

  # POST /refactorings
  # POST /refactorings.xml
  def create
    @refactoring = Refactoring.new(params[:refactoring])

    respond_to do |format|
      if @refactoring.save
        format.html { redirect_to(snippet_refactoring_path(@refactoring.snippet, @refactoring), :notice => 'Refactoring was successfully created.') }
        format.xml  { render :xml => @refactoring, :status => :created, :location => @refactoring }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @refactoring.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /refactorings/1
  # PUT /refactorings/1.xml
  def update
    @refactoring = Refactoring.find(params[:id])

    respond_to do |format|
      if @refactoring.update_attributes(params[:refactoring])
        format.html { redirect_to(@refactoring, :notice => 'Refactoring was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @refactoring.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /refactorings/1
  # DELETE /refactorings/1.xml
  def destroy
    @refactoring = Refactoring.find(params[:id])
    @refactoring.destroy

    respond_to do |format|
      format.html { redirect_to(refactorings_url) }
      format.xml  { head :ok }
    end
  end

  private

  def capture_snippet
    @snippet = Snippet.find(params[:snippet_id]) if params[:snippet_id]
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  # GET /snippets
  # GET /snippets.xml
  def index
    @snippets = Snippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.xml
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.xml
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.xml
  def create
    @snippet = Snippet.new(params[:snippet])

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to(@snippet, :notice => 'Snippet was successfully created.') }
        format.xml  { render :xml => @snippet, :status => :created, :location => @snippet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.xml
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to(@snippet, :notice => 'Snippet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.xml
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to(snippets_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/refactorings_helper.rb
module RefactoringsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Refactor</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="flash_container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/refactorings/_form.html.erb
<%= form_for [:snippet, @refactoring] do |f| %>
  <% if @refactoring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@refactoring.errors.count, "error") %> prohibited this refactoring from being saved:</h2>

      <ul>
      <% @refactoring.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :snippet_id %><br />
    <%= f.text_field :snippet_id %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :karma %><br />
    <%= f.text_field :karma %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/refactorings/edit.html.erb
<h1>Editing refactoring</h1>

<%= render 'form' %>

<%= link_to 'Show', snippet_refactoring_path(@refactoring.snippet, @refactoring) %> |
<%= link_to 'Back', snippet_refactorings_path(@snippet) %>

app/views/refactorings/index.html.erb
<h1>Listing refactorings</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Comment</th>
    <th>Snippet</th>
    <th>Language</th>
    <th>User</th>
    <th>Karma</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @refactorings.each do |refactoring| %>
  <tr>
    <td><%= refactoring.body %></td>
    <td><%= refactoring.comment %></td>
    <td><%= refactoring.snippet_id %></td>
    <td><%= refactoring.language %></td>
    <td><%= refactoring.user_id %></td>
    <td><%= refactoring.karma %></td>
    <td><%= link_to 'Show', snippet_refactoring_path(@snippet, refactoring) %></td>
    <td><%= link_to 'Edit', edit_snippet_refactoring_path(@snippet, refactoring) %></td>
    <td><%= link_to 'Destroy', snippet_refactoring_path(@snippet, refactoring), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Refactoring', new_snippet_refactoring_path(@snippet) %>

app/views/refactorings/new.html.erb
<h1>New refactoring</h1>

<%= render 'form' %>

<%= link_to 'Back', snippet_refactorings_path(@snippet) %>

app/views/refactorings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @refactoring.body %>
</p>

<p>
  <b>Comment:</b>
  <%= @refactoring.comment %>
</p>

<p>
  <b>Snippet:</b>
  <%= @refactoring.snippet_id %>
</p>

<p>
  <b>Language:</b>
  <%= @refactoring.language %>
</p>

<p>
  <b>User:</b>
  <%= @refactoring.user_id %>
</p>

<p>
  <b>Karma:</b>
  <%= @refactoring.karma %>
</p>


<%= link_to 'Edit', edit_snippet_refactoring_path(@refactoring.snippet, @refactoring) %> |
<%= link_to 'Back', snippet_refactorings_path(@snippet) %>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :karma %><br />
    <%= f.text_field :karma %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>Listing snippets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Notes</th>
    <th>Language</th>
    <th>User</th>
    <th>Karma</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.title %></td>
    <td><%= snippet.body %></td>
    <td><%= snippet.notes %></td>
    <td><%= snippet.language %></td>
    <td><%= snippet.user_id %></td>
    <td><%= snippet.karma %></td>
    <td><%= link_to 'Show', snippet %></td>
    <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
    <td><%= link_to 'Destroy', snippet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @snippet.title %>
</p>

<p>
  <b>Body:</b>
  <%= @snippet.body %>
</p>

<p>
  <b>Notes:</b>
  <%= @snippet.notes %>
</p>

<p>
  <b>Language:</b>
  <%= @snippet.language %>
</p>

<p>
  <b>User:</b>
  <%= @snippet.user_id %>
</p>

<p>
  <b>Karma:</b>
  <%= @snippet.karma %>
</p>


<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>

app/views/welcome/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>:
  <%= link_to 'Sign Out', destroy_user_session_url %>
<% else %>
  <%= link_to 'Sign In', new_user_session_url %> or
  <%= link_to 'Register', new_user_registration_url %>
<% end %>